version: '3.8'

services:
  portfolio-backend:
    build: .
    container_name: portfolio-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GIN_MODE=debug
      - MONGODB_URI=mongodb+srv://anandtiwari3399:Anand.01@anand-portfolio.jyac0ao.mongodb.net/
      - MONGODB_DATABASE=portfolio_db
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
      - JWT_EXPIRY=24h
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
    volumes:
      - ./.env:/app/.env:ro

networks:
  default:
    driver: bridge 